### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by zodiacfireworks** [mapmeld/fortran-machine#16]
Hello!

I wanted to work with this for a bit of fun (I :heart: Fortran), but I couldn't help but notice that the website is down.

Can I help you in any way with the web?

![image](https://user-images.githubusercontent.com/4976355/169626157-ea4df2b3-8a5c-413c-8591-691b8c0a7172.png)

**Comment by mapmeld** [comment]
Thanks for reporting this. I was traveling and just fixed it now.
