### ISSUE TITLE
FORTRAN.io website marsupial search is missing wombat

### ISSUE THREAD

**Issue by saghm** [mapmeld/fortran-machine#3]
Hi! Sorry if this is the wrong place for this issue, but I came across the [fortan.io](https://fortran.io) website on Hacker News, and I noticed that in the marsupial search there are no results when you search ["wombat"](https://en.wikipedia.org/wiki/Wombat). While "wombat" is indeed an ugly name for an animal, I can assure you that wombats themselves are actually quite adorable, as shown [here out in the wild](http://pawn.hss.cmu.edu/~67103/images/wombats/wombat1.jpg), [here in baby form](http://chirpnews.com/wp-content/uploads/2016/03/Megan-baby-wombat-Flinders-Island-Sammi-Gowthorp-Visit-Flinders-Island-Tasmania-May-16-1024x682.jpg), and [here with Steve Irwin, the Crocodile Hunter](http://pawn.hss.cmu.edu/~67103/images/wombats/wombat5.jpg). I'm sure this error was purely accidental, so I hope you'll consider adding a wombat entry to your search for the delight of all your users. Thanks!

**Comment by mapmeld** [comment]
this is the right place to ask!  I only added a few marsupials manually, so these guys got overlooked

consider this issue mission-critical and now solved: https://fortran.io/search?q=wombat
