### ISSUE TITLE
fortran.io is down

### ISSUE THREAD

**Issue by millerjs** [mapmeld/fortran-machine#4]
Getting a 502 when accessing [fortran.io](https://fortran.io/)

**Comment by mapmeld** [comment]
thanks for the report! now fixed

**Comment by oliverbenns** [comment]
Still 502 for me!

**Comment by mapmeld** [comment]
@oliverbenns should be fixed now, thanks!

**Comment by oliverbenns** [comment]
Awesome! Thank you :)

**Comment by mishazawa** [comment]
@mapmeld site is down again(

**Comment by mapmeld** [comment]
@mishazawa thanks for letting me know! It's back online again
